name       : intel-gpu-tools
version    : 1.19
release    : 2
homepage   : https://cgit.freedesktop.org/xorg/app/intel-gpu-tools/
source     :
    - https://www.x.org/releases/individual/app/intel-gpu-tools-1.19.tar.gz : 70f6ecb45c5689a384402b9f103cf748c263d424a1cbc9bf11ce01b8082388da
license    : MIT
component  : system.utils
summary    : Tools for development and testing of the Intel DRM driver
description: |
    Tools for development and testing of the Intel DRM driver
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(libdrm)
    - pkgconfig(libkmod)
    - pkgconfig(libunwind)
    - pkgconfig(pciaccess)
    - pkgconfig(python3)
    - pkgconfig(xorg-macros)
    - swig
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
