name       : intel-gpu-tools
version    : '1.22'
release    : 4
homepage   : https://cgit.freedesktop.org/xorg/app/intel-gpu-tools/
source     :
    - https://www.x.org/releases/individual/app/intel-gpu-tools-1.22.tar.xz : 3d66c1dc5110712ca4d22199b3ce9853f261be1690064edf87e69e5392e39a5c
license    : MIT
component  : system.utils
summary    : Tools for development and testing of the Intel DRM driver
description: |
    Tools for development and testing of the Intel DRM driver
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk-doc)
    - pkgconfig(libdrm)
    - pkgconfig(libkmod)
    - pkgconfig(libunwind)
    - pkgconfig(pciaccess)
    - pkgconfig(libprocps)
    - pkgconfig(python3)
    - pkgconfig(xorg-macros)
    - swig
libsplit   : no
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
