name       : intel-gpu-tools
version    : 1.3
release    : 1
homepage   : https://cgit.freedesktop.org/xorg/app/intel-gpu-tools/
source     :
    - https://github.com/ChrisCummins/intel-gpu-tools/archive/intel-gpu-tools-1.3.tar.gz : 2ddd2126fd849ca1e067a289f55b73c392d5fac5acf0400dd2c578010b26106c
license    : MIT
summary    : Tools for development and testing of the Intel DRM driver
description: |
    Tools for development and testing of the Intel DRM driver
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(libdrm)
    - pkgconfig(libunwind)
    - pkgconfig(pciaccess)
    - pkgconfig(xorg-macros)
    - python3-devel
    - swig
setup      : |
    ./autogen.sh $CONFOPTS
build      : |
    %make
install    : |
    %make_install
