name       : intel-gpu-tools
version    : '1.25'
release    : 8
homepage   : https://cgit.freedesktop.org/xorg/app/intel-gpu-tools/
source     :
    - https://gitlab.freedesktop.org/drm/igt-gpu-tools/-/archive/igt-gpu-tools-1.25/igt-gpu-tools-igt-gpu-tools-1.25.tar.gz : df2b8528220c26d26d6e891998a2292251fe81fccde4066fc21303b656aaeea4
license    : MIT
component  : system.utils
summary    : Tools for development and testing of the Intel DRM driver
description: |
    Tools for development and testing of the Intel DRM driver
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk-doc)
    - pkgconfig(libdrm)
    - pkgconfig(libkmod)
    - pkgconfig(libunwind)
    - pkgconfig(pciaccess)
    - pkgconfig(libprocps)
    - pkgconfig(python3)
    - pkgconfig(xorg-macros)
    - elfutils-devel
    - swig
libsplit   : no
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check || :
